"""
Pre-size every page-header (hero) photo so it is served as a plain static
file from the CDN — no on-demand image optimization, so headers paint
immediately even on a fresh deployment.

For each hero image it writes:
  public/assets/images/_hero/<name>-<width>.avif + .webp   (640/1080/1600/1920, capped at source width)
and src/data/heroImages.js with the srcset and a tiny blurred preview
(data URI) shown while the photo loads.

Hero images are found automatically: PageHero `image=`/`portraitImage=`
props in src/app, the retreat detail images, the home hero stills and the
blog article header images.

usage: python scripts/make-hero-images.py
"""
import base64
import io
import json
import os
import re
import subprocess

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PUBLIC = os.path.join(ROOT, "public")
OUT_DIR = os.path.join(PUBLIC, "assets", "images", "_hero")
WIDTHS = [640, 1080, 1600, 1920]
# AVIF q62 ≈ SSIM 0.978 at ~1/3 less weight than WebP q80 (the fallback).
AVIF_QUALITY = 62
WEBP_QUALITY = 80


def read(path):
    with open(os.path.join(ROOT, path), encoding="utf8") as f:
        return f.read()


def collect():
    found = set()
    for dirpath, _, files in os.walk(os.path.join(ROOT, "src", "app")):
        for name in files:
            if name.endswith(".jsx"):
                text = read(os.path.relpath(os.path.join(dirpath, name), ROOT))
                for block in re.findall(r"<PageHero(.*?)/>", text, re.S):
                    found.update(re.findall(r'(?:image|portraitImage)="(/assets/[^"]+)"', block))
    hero = read("src/components/sections/home/HomeHero.jsx")
    found.update(re.findall(r'"(/assets/images/hero/villas-aerial[^"]*\.webp)"', hero))
    # Retreat detail pages use retreats[*].image.
    out = subprocess.run(
        ["node", "-e", "import('./src/data/retreats.js').then(m=>console.log(JSON.stringify(Object.values(m.retreats).map(r=>r.image))))"],
        cwd=ROOT, capture_output=True, text=True,
    ).stdout.strip().splitlines()[-1]
    found.update(json.loads(out))
    # Blog article headers use each post's image.
    for img in re.findall(r'post\("[^"]*", "[^"]*", "([^"]+)"', read("src/data/community.js")):
        found.add(f"/assets/images/blog/{img}.webp")
    found.add("/assets/images/practice/rice-walk.webp")  # article fallback
    return sorted(found)


def blur_uri(im):
    small = im.convert("RGB")
    small.thumbnail((24, 24), Image.LANCZOS)
    buf = io.BytesIO()
    small.save(buf, "WEBP", quality=40)
    return "data:image/webp;base64," + base64.b64encode(buf.getvalue()).decode()


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    data = {}
    for src in collect():
        path = os.path.join(PUBLIC, src.lstrip("/"))
        if not os.path.exists(path):
            print("missing", src)
            continue
        im = Image.open(path).convert("RGB")
        base = re.sub(r"[^a-z0-9-]", "-", os.path.splitext(src.split("/assets/images/", 1)[1])[0].lower())
        widths = [w for w in WIDTHS if w < im.width] + [min(im.width, WIDTHS[-1])]
        srcset, avif = [], []
        for w in sorted(set(widths)):
            resized = im if w == im.width else im.resize((w, round(im.height * w / im.width)), Image.LANCZOS)
            resized.save(os.path.join(OUT_DIR, f"{base}-{w}.webp"), "WEBP", quality=WEBP_QUALITY, method=6)
            resized.save(os.path.join(OUT_DIR, f"{base}-{w}.avif"), "AVIF", quality=AVIF_QUALITY, speed=4)
            srcset.append([w, f"/assets/images/_hero/{base}-{w}.webp"])
            avif.append([w, f"/assets/images/_hero/{base}-{w}.avif"])
        data[src] = {"width": im.width, "height": im.height, "srcset": srcset, "avif": avif, "blur": blur_uri(im)}
        print(src, "->", [w for w, _ in srcset])
    lines = [
        "// Generated by scripts/make-hero-images.py — pre-sized page-header photos",
        "// served as static files, plus a blurred preview shown while they load.",
        "",
        "const heroImages = " + json.dumps(data, indent=1) + ";",
        "",
        "export default heroImages;",
        "",
    ]
    with open(os.path.join(ROOT, "src", "data", "heroImages.js"), "w", encoding="utf8") as f:
        f.write("\n".join(lines))
    print(len(data), "hero images")


if __name__ == "__main__":
    main()
